[2025-06-26 00:21:36,396: INFO: main: welcome to our custom log]
[2025-06-26 09:05:24,800: INFO: main: welcome to our custom log]
[2025-06-26 09:29:45,139: INFO: main: welcome to our custom log]
[2025-06-26 11:33:16,594: INFO: main: welcome to our custom log]
[2025-06-26 16:44:04,373: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-26 16:44:04,392: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-26 16:44:04,396: INFO: common: created directory at: artifacts]
[2025-06-26 16:44:04,399: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-26 16:44:04,402: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-26 16:48:31,237: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-26 17:47:40,962: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-26 17:47:40,970: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-26 17:47:40,977: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-26 17:47:40,980: INFO: common: created directory at: artifacts]
[2025-06-26 17:47:40,982: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-26 17:47:40,985: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-26 17:51:50,171: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-26 17:52:19,764: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-26 20:20:12,910: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-26 20:20:12,922: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-26 20:20:12,924: INFO: common: created directory at: artifacts]
[2025-06-26 20:20:12,926: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-26 20:20:32,601: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-26 20:33:27,521: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-26 20:33:27,522: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-26 20:33:27,524: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-26 20:33:27,524: INFO: common: created directory at: artifacts]
[2025-06-26 20:33:27,525: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-26 20:33:27,526: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-26 20:38:18,156: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-26 20:38:28,509: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-26 20:38:28,510: INFO: main: *******************]
[2025-06-26 20:38:28,510: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-26 20:38:28,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-26 20:38:28,512: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-26 20:38:28,513: INFO: common: created directory at: artifacts]
[2025-06-26 20:38:28,513: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-26 20:38:29,100: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-26 20:38:29,349: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-28 22:26:25,260: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:26:25,287: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:26:25,292: INFO: common: created directory at: artifacts]
[2025-06-28 22:26:25,297: INFO: common: created directory at: artifacts\training]
[2025-06-28 22:28:53,278: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:28:53,281: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:28:53,283: INFO: common: created directory at: artifacts]
[2025-06-28 22:28:53,285: INFO: common: created directory at: artifacts\training]
[2025-06-28 22:29:57,366: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 22:29:57,385: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 22:29:57,388: INFO: common: created directory at: artifacts]
[2025-06-28 22:29:57,392: INFO: common: created directory at: artifacts\training]
[2025-06-28 23:00:58,290: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-28 23:00:58,297: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 23:00:58,299: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 23:00:58,301: INFO: common: created directory at: artifacts]
[2025-06-28 23:00:58,302: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-28 23:00:58,303: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-28 23:09:58,902: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-28 23:10:35,952: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-28 23:10:35,953: INFO: main: *******************]
[2025-06-28 23:10:35,954: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-28 23:10:35,958: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 23:10:35,964: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 23:10:35,966: INFO: common: created directory at: artifacts]
[2025-06-28 23:10:35,968: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-28 23:10:37,562: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-28 23:10:38,125: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-28 23:10:38,127: INFO: main: *******************]
[2025-06-28 23:10:38,128: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-06-28 23:10:38,133: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-28 23:10:38,138: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-28 23:10:38,139: INFO: common: created directory at: artifacts]
[2025-06-28 23:10:38,141: INFO: common: created directory at: artifacts\training]
[2025-06-28 23:50:16,530: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-07 20:53:04,895: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-07 20:53:04,901: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-07 20:53:04,904: INFO: common: created directory at: artifacts]
[2025-07-07 21:03:12,008: INFO: common: json file saved at: scores.json]
[2025-07-07 21:03:21,238: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-07 21:03:23,487: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmp3scibm19\model\data\model\assets]
[2025-07-07 21:31:36,627: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-07 21:31:36,632: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-07 21:31:36,635: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-07 21:31:36,636: INFO: common: created directory at: artifacts]
[2025-07-07 21:31:36,637: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-07 21:31:36,638: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-07 21:37:55,200: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-07 21:38:10,047: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-07 21:38:10,048: INFO: main: *******************]
[2025-07-07 21:38:10,048: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-07 21:38:10,052: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-07 21:38:10,054: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-07 21:38:10,056: INFO: common: created directory at: artifacts]
[2025-07-07 21:38:10,056: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-07 21:38:10,811: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-07 21:38:11,142: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-07 21:38:11,143: INFO: main: *******************]
[2025-07-07 21:38:11,143: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-07 21:38:11,145: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-07 21:38:11,147: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-07 21:38:11,148: INFO: common: created directory at: artifacts]
[2025-07-07 21:38:11,149: INFO: common: created directory at: artifacts\training]
[2025-07-07 21:38:11,766: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "C:\kidney-tumor\main.py", line 35, in <module>
    model_trainer.main()
  File "c:\kidney-tumor\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "c:\kidney-tumor\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2025-07-07 22:13:56,748: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-07 22:13:56,754: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-07 22:13:56,758: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-07 22:13:56,767: INFO: common: created directory at: artifacts]
[2025-07-07 22:13:56,780: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-07 22:13:56,781: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-07 22:30:14,563: ERROR: main: ('Connection broken: IncompleteRead(721103531 bytes read, 219271975 more expected)', IncompleteRead(721103531 bytes read, 219271975 more expected))]
Traceback (most recent call last):
  File "C:\kidney-tumor\.venv\lib\site-packages\urllib3\response.py", line 779, in _error_catcher
    yield
  File "C:\kidney-tumor\.venv\lib\site-packages\urllib3\response.py", line 925, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(721103531 bytes read, 219271975 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\kidney-tumor\.venv\lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\kidney-tumor\.venv\lib\site-packages\urllib3\response.py", line 1091, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\kidney-tumor\.venv\lib\site-packages\urllib3\response.py", line 1008, in read
    data = self._raw_read(amt)
  File "C:\kidney-tumor\.venv\lib\site-packages\urllib3\response.py", line 903, in _raw_read
    with self._error_catcher():
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\kidney-tumor\.venv\lib\site-packages\urllib3\response.py", line 803, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(721103531 bytes read, 219271975 more expected)', IncompleteRead(721103531 bytes read, 219271975 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\kidney-tumor\main.py", line 11, in <module>
    obj.main()
  File "c:\kidney-tumor\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "c:\kidney-tumor\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "c:\kidney-tumor\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\kidney-tumor\.venv\lib\site-packages\gdown\download.py", line 368, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "C:\kidney-tumor\.venv\lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(721103531 bytes read, 219271975 more expected)', IncompleteRead(721103531 bytes read, 219271975 more expected))
[2025-07-07 22:31:26,603: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-07 22:31:26,606: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-07 22:31:26,608: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-07 22:31:26,609: INFO: common: created directory at: artifacts]
[2025-07-07 22:31:26,609: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-07 22:31:26,611: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-07 22:36:44,012: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-07 22:37:18,381: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-07 22:37:18,381: INFO: main: *******************]
[2025-07-07 22:37:18,382: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-07 22:37:18,387: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-07 22:37:18,397: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-07 22:37:18,400: INFO: common: created directory at: artifacts]
[2025-07-07 22:37:18,403: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-07 22:37:19,957: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-07 22:37:20,951: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-07 22:37:20,952: INFO: main: *******************]
[2025-07-07 22:37:20,953: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-07 22:37:20,957: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-07 22:37:20,966: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-07 22:37:20,969: INFO: common: created directory at: artifacts]
[2025-07-07 22:37:20,970: INFO: common: created directory at: artifacts\training]
[2025-07-07 23:28:27,260: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-07 23:28:27,263: INFO: main: *******************]
[2025-07-07 23:28:27,263: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-07 23:28:27,269: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-07 23:28:27,274: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-07 23:28:27,276: INFO: common: created directory at: artifacts]
[2025-07-07 23:35:45,165: INFO: common: json file saved at: scores.json]
[2025-07-07 23:35:45,168: INFO: common: json file saved at: scores.json]
[2025-07-07 23:35:45,168: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-07 23:38:48,068: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-07 23:38:48,080: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-07 23:38:48,083: INFO: common: created directory at: artifacts]
[2025-07-07 23:50:17,856: INFO: common: json file saved at: scores.json]
[2025-07-07 23:50:25,995: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-07 23:50:29,055: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpsv8362i5\model\data\model\assets]
[2025-07-08 13:19:19,554: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-08 13:19:19,585: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 13:19:19,614: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 13:19:19,618: INFO: common: created directory at: artifacts]
[2025-07-08 13:19:19,623: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-08 13:19:19,626: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-08 13:25:46,937: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-08 13:26:55,613: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-08 13:26:55,615: INFO: main: *******************]
[2025-07-08 13:26:55,616: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-08 13:26:55,622: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 13:26:55,629: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 13:26:55,633: INFO: common: created directory at: artifacts]
[2025-07-08 13:26:55,637: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-08 13:26:59,860: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-08 13:27:01,345: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-08 13:27:01,355: INFO: main: *******************]
[2025-07-08 13:27:01,374: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-08 13:27:01,398: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 13:27:01,427: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 13:27:01,439: INFO: common: created directory at: artifacts]
[2025-07-08 13:27:01,502: INFO: common: created directory at: artifacts\training]
[2025-07-08 14:12:52,645: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-08 14:12:52,647: INFO: main: *******************]
[2025-07-08 14:12:52,647: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-08 14:12:52,675: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 14:12:52,693: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 14:12:52,700: INFO: common: created directory at: artifacts]
[2025-07-08 14:17:58,092: INFO: common: json file saved at: scores.json]
[2025-07-08 14:17:58,094: INFO: common: json file saved at: scores.json]
[2025-07-08 14:17:58,094: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-08 14:50:01,432: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-08 14:50:01,438: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 14:50:01,443: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 14:50:01,446: INFO: common: created directory at: artifacts]
[2025-07-08 14:50:01,447: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-08 14:50:01,449: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-08 14:57:26,994: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-08 14:58:18,213: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-08 14:58:18,215: INFO: main: *******************]
[2025-07-08 14:58:18,217: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-08 14:58:18,229: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 14:58:18,231: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 14:58:18,234: INFO: common: created directory at: artifacts]
[2025-07-08 14:58:18,235: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-08 14:58:19,946: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-08 14:58:20,461: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-08 14:58:20,462: INFO: main: *******************]
[2025-07-08 14:58:20,463: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-08 14:58:20,473: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 14:58:20,477: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 14:58:20,480: INFO: common: created directory at: artifacts]
[2025-07-08 14:58:20,483: INFO: common: created directory at: artifacts\training]
[2025-07-08 15:36:36,908: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-08 15:36:36,910: INFO: main: *******************]
[2025-07-08 15:36:36,910: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-08 15:36:36,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 15:36:36,917: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 15:36:36,919: INFO: common: created directory at: artifacts]
[2025-07-08 15:41:15,633: INFO: common: json file saved at: scores.json]
[2025-07-08 15:41:15,634: INFO: common: json file saved at: scores.json]
[2025-07-08 15:41:15,634: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-08 16:30:31,190: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-08 16:30:31,195: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 16:30:31,197: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 16:30:31,199: INFO: common: created directory at: artifacts]
[2025-07-08 16:30:31,200: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-08 16:30:31,201: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-08 16:38:04,152: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-08 16:39:00,415: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-08 16:39:00,416: INFO: main: *******************]
[2025-07-08 16:39:00,420: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-08 16:39:00,427: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 16:39:00,431: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 16:39:00,432: INFO: common: created directory at: artifacts]
[2025-07-08 16:39:00,435: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-08 16:39:02,687: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-08 16:39:03,954: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-08 16:39:03,955: INFO: main: *******************]
[2025-07-08 16:39:03,956: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-08 16:39:03,962: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 16:39:03,966: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 16:39:03,968: INFO: common: created directory at: artifacts]
[2025-07-08 16:39:03,971: INFO: common: created directory at: artifacts\training]
[2025-07-08 17:29:52,881: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-08 17:29:52,884: INFO: main: *******************]
[2025-07-08 17:29:52,885: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-08 17:29:52,894: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 17:29:52,900: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 17:29:52,903: INFO: common: created directory at: artifacts]
[2025-07-08 17:40:21,887: INFO: common: json file saved at: scores.json]
[2025-07-08 17:40:21,889: INFO: common: json file saved at: scores.json]
[2025-07-08 17:40:21,890: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-08 17:41:53,491: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 17:41:53,497: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 17:41:53,500: INFO: common: created directory at: artifacts]
[2025-07-08 17:50:09,112: INFO: common: json file saved at: scores.json]
[2025-07-08 17:50:16,289: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-08 17:50:23,743: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmpnkun0j0k\model\data\model\assets]
[2025-07-08 17:55:16,108: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-08 17:55:16,113: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 17:55:16,130: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 17:55:16,132: INFO: common: created directory at: artifacts]
[2025-07-08 17:55:16,133: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-08 17:55:16,135: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-08 18:01:35,320: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-08 18:02:36,796: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-08 18:02:36,797: INFO: main: *******************]
[2025-07-08 18:02:36,799: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-08 18:02:36,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 18:02:36,816: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 18:02:36,822: INFO: common: created directory at: artifacts]
[2025-07-08 18:02:36,840: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-08 18:02:39,435: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-08 18:02:40,678: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-08 18:02:40,679: INFO: main: *******************]
[2025-07-08 18:02:40,679: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-08 18:02:40,684: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-08 18:02:40,704: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-08 18:02:40,707: INFO: common: created directory at: artifacts]
[2025-07-08 18:02:40,716: INFO: common: created directory at: artifacts\training]
[2025-07-11 18:27:38,626: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-11 18:27:38,629: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-11 18:27:38,635: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-11 18:27:38,639: INFO: common: created directory at: artifacts]
[2025-07-11 18:27:38,641: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-11 18:27:38,643: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-11 18:33:34,664: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-11 18:33:34,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-11 18:33:34,669: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-11 18:33:34,670: INFO: common: created directory at: artifacts]
[2025-07-11 18:33:34,670: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-11 18:33:34,672: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-11 18:38:11,924: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-11 18:38:36,107: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-11 18:41:20,883: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-11 18:41:20,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-11 18:41:20,887: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-11 18:41:20,888: INFO: common: created directory at: artifacts]
[2025-07-11 18:41:20,889: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-11 18:41:20,889: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-11 18:41:40,003: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-11 18:41:40,006: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-11 18:41:40,008: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-11 18:41:40,009: INFO: common: created directory at: artifacts]
[2025-07-11 18:41:40,011: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-11 18:41:40,014: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-11 18:46:30,926: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1dkE79W8XToiv0IesetUyDNmTUQLehSla/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-11 18:47:24,888: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-11 18:51:50,818: INFO: stage_02_prepare_base_model: *******************]
[2025-07-11 18:51:50,819: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base model started <<<<<<]
[2025-07-11 18:51:50,824: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-11 18:51:50,828: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-11 18:51:50,832: INFO: common: created directory at: artifacts]
[2025-07-11 18:51:50,835: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-11 18:51:52,624: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-11 18:51:53,093: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base model completed <<<<<<

x==========x]
[2025-07-11 18:52:06,460: INFO: stage_03_model_training: *******************]
[2025-07-11 18:52:06,460: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-07-11 18:52:06,466: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-11 18:52:06,475: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-11 18:52:06,476: INFO: common: created directory at: artifacts]
[2025-07-11 18:52:06,477: INFO: common: created directory at: artifacts\training]
[2025-07-11 19:58:22,000: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-11 19:58:35,496: INFO: stage_04_model_evaluation: *******************]
[2025-07-11 19:58:35,497: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-11 19:58:35,499: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-11 19:58:35,500: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-11 19:58:35,501: INFO: common: created directory at: artifacts]
[2025-07-11 20:03:00,792: INFO: common: json file saved at: scores.json]
[2025-07-11 20:03:00,794: INFO: common: json file saved at: scores.json]
[2025-07-11 20:03:01,996: ERROR: stage_04_model_evaluation: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "C:\kidney-tumor\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 30, in <module>
    obj.main()
  File "C:\kidney-tumor\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\kidney-tumor\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\kidney-tumor\.venv\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\kidney-tumor\.venv\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\kidney-tumor\.venv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\kidney-tumor\.venv\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\kidney-tumor\.venv\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\kidney-tumor\.venv\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\kidney-tumor\.venv\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-07-11 20:20:51,379: INFO: stage_04_model_evaluation: *******************]
[2025-07-11 20:20:51,380: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-11 20:20:51,401: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-11 20:20:51,403: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-11 20:20:51,404: INFO: common: created directory at: artifacts]
[2025-07-11 20:24:56,220: INFO: common: json file saved at: scores.json]
[2025-07-11 20:24:56,222: INFO: common: json file saved at: scores.json]
[2025-07-11 20:24:59,276: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-07-11 20:24:59,859: INFO: builder_impl: Assets written to: C:\Users\DELL\AppData\Local\Temp\tmptbbkv20v\model\data\model\assets]
[2025-07-11 20:25:58,481: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-11 20:35:38,867: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.64:8080]
[2025-07-11 20:35:38,868: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-07-11 20:35:50,405: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:35:50] "GET / HTTP/1.1" 200 -]
[2025-07-11 20:36:04,384: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\kidney-tumor\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\kidney-tumor\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-07-11 20:36:04,466: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:36:04] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-07-11 20:37:28,267: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:37:28] "GET / HTTP/1.1" 200 -]
[2025-07-11 20:37:30,210: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\kidney-tumor\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\kidney-tumor\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-07-11 20:37:30,217: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:37:30] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-07-11 20:37:33,579: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:37:33] "GET / HTTP/1.1" 200 -]
[2025-07-11 20:37:49,000: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\kidney-tumor\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\kidney-tumor\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-07-11 20:37:49,003: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:37:49] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-07-11 20:39:17,191: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:39:17] "GET / HTTP/1.1" 200 -]
[2025-07-11 20:39:33,456: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\kidney-tumor\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\kidney-tumor\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-07-11 20:39:33,462: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:39:33] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-07-11 20:40:36,332: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.64:8080]
[2025-07-11 20:40:36,332: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-07-11 20:40:41,099: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:40:41] "GET / HTTP/1.1" 200 -]
[2025-07-11 20:40:59,798: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\kidney-tumor\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\kidney-tumor\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-07-11 20:40:59,811: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:40:59] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-07-11 20:45:05,627: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.64:8080]
[2025-07-11 20:45:05,628: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-07-11 20:45:09,268: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:45:09] "GET / HTTP/1.1" 200 -]
[2025-07-11 20:45:15,933: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\kidney-tumor\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\kidney-tumor\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-07-11 20:45:15,948: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:45:15] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-07-11 20:46:52,147: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.64:8080]
[2025-07-11 20:46:52,147: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-07-11 20:47:13,995: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:47:13] "GET / HTTP/1.1" 200 -]
[2025-07-11 20:47:21,233: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\kidney-tumor\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\kidney-tumor\.venv\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\kidney-tumor\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\kidney-tumor\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\kidney-tumor\.venv\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-07-11 20:47:21,248: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:47:21] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-07-11 20:49:31,927: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.64:8080]
[2025-07-11 20:49:31,928: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-07-11 20:49:40,423: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:49:40] "GET / HTTP/1.1" 200 -]
[2025-07-11 20:49:49,022: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:49:49] "POST /predict HTTP/1.1" 200 -]
[2025-07-11 20:50:18,253: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:50:18] "POST /predict HTTP/1.1" 200 -]
[2025-07-11 20:50:35,716: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:50:35] "POST /predict HTTP/1.1" 200 -]
[2025-07-11 20:50:50,293: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:50:50] "POST /predict HTTP/1.1" 200 -]
[2025-07-11 20:51:00,605: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001E8A3D605E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-07-11 20:51:00,614: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:51:00] "POST /predict HTTP/1.1" 200 -]
[2025-07-11 20:58:48,813: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.64:8080]
[2025-07-11 20:58:48,813: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-07-11 20:59:09,092: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:59:09] "GET / HTTP/1.1" 200 -]
[2025-07-11 20:59:17,535: INFO: _internal: 127.0.0.1 - - [11/Jul/2025 20:59:17] "POST /predict HTTP/1.1" 200 -]
